import { registerHooks } from "node:module";
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";

registerHooks({
  resolve(specifier, context, nextResolve) {
    if (specifier.startsWith("@/")) {
      const target = pathToFileURL(resolve(process.cwd(), `${specifier.slice(2)}.ts`)).href;
      return nextResolve(target, context);
    }
    try {
      return nextResolve(specifier, context);
    } catch (error) {
      if (specifier.startsWith("./") || specifier.startsWith("../")) {
        return nextResolve(`${specifier}.ts`, context);
      }
      throw error;
    }
  },
});

const { normalizeSlug, resolveSlug, uniqueSlugCandidate } = await import("./lib/slug.ts");
const { resolveUniqueSlug } = await import("./lib/slug-server.ts");
const { prisma } = await import("./lib/prisma.ts");

let failures = 0;
function check(name: string, actual: unknown, expected: unknown) {
  const ok = actual === expected;
  if (!ok) failures += 1;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${ok ? "" : `  (got ${JSON.stringify(actual)}, want ${JSON.stringify(expected)})`}`);
}

check("space runs", normalizeSlug("تست   تست"), "تست-تست");
check("leading/trailing spaces", normalizeSlug(" تست تست "), "تست-تست");
check("hyphen with spaces", normalizeSlug("تست- - تست"), "تست-تست");
check("persian punctuation", normalizeSlug("تست، تست!"), "تست-تست");
check("persian title", normalizeSlug("ضربه دولیو چاگی در تکواندو"), "ضربه-دولیو-چاگی-در-تکواندو");
check("water tag", normalizeSlug("آب رسانی"), "آب-رسانی");
check("form tag", normalizeSlug("اصلاح فرم"), "اصلاح-فرم");
check("latin", normalizeSlug("  Hello   World!  "), "hello-world");
check("numeric", normalizeSlug("123"), "123");
check("persian numeric", normalizeSlug("۱۲۳"), "۱۲۳");
check("mixed", normalizeSlug("تست Test 42"), "تست-test-42");
check("zwnj preserved", normalizeSlug("تکنیک‌ها"), "تکنیک‌ها");
check("zwnj next to hyphen", normalizeSlug("تکنیک‌ -ها"), "تکنیک-ها");
check("underscore", normalizeSlug("foo_bar"), "foo-bar");
check("slash", normalizeSlug("foo/bar"), "foo-bar");
check("apostrophe", normalizeSlug("don't stop"), "don-t-stop");
check("caps", normalizeSlug("My-Post 2"), "my-post-2");
check("arabic diacritics", normalizeSlug("تَستٌ"), "تست");
check("punctuation only", normalizeSlug("!!! ؟؟؟"), "");
check("empty", normalizeSlug("   "), "");
check("idempotent", normalizeSlug(normalizeSlug("تست   تست- -x!")), "تست-تست-x");

check("auto from title", resolveSlug("", "ضربه دولیو چاگی در تکواندو").ok && (resolveSlug("", "ضربه دولیو چاگی در تکواندو") as { slug: string }).slug, "ضربه-دولیو-چاگی-در-تکواندو");
check("auto flag", (resolveSlug("", "تست تست") as { autoGenerated: boolean }).autoGenerated, true);
check("manual persian", (resolveSlug("دستی-اسلاگ", "x") as { slug: string }).slug, "دستی-اسلاگ");
check("manual english", (resolveSlug("my-slug", "x") as { slug: string }).slug, "my-slug");
check("manual numeric", (resolveSlug("123", "x") as { slug: string }).slug, "123");
check("manual normalized", (resolveSlug("  My Slug  ", "x") as { slug: string }).slug, "my-slug");
const manualInvalid = resolveSlug("!!!", "x");
check("manual invalid", manualInvalid.ok || manualInvalid.reason !== "invalid", false);
const autoEmpty = resolveSlug("", "!!!");
check("auto empty source", autoEmpty.ok || autoEmpty.reason !== "empty", false);

check("candidate free", uniqueSlugCandidate("abc", []), "abc");
check("candidate -2", uniqueSlugCandidate("تست-تست", ["تست-تست"]), "تست-تست-2");
check("candidate -3", uniqueSlugCandidate("تست-تست", ["تست-تست", "تست-تست-2"]), "تست-تست-3");
check("candidate -4", uniqueSlugCandidate("تست-تست", ["تست-تست", "تست-تست-2", "تست-تست-3"]), "تست-تست-4");
check("candidate gap", uniqueSlugCandidate("x", ["x", "x-5"]), "x-6");
check("candidate suffix ignored", uniqueSlugCandidate("x", ["x", "x-other"]), "x-2");

const MARK = "slugflow-test";

async function cleanup() {
  await prisma.post.deleteMany({
    where: { OR: [{ slug: { contains: MARK } }, { slug: { startsWith: "تست-تست" } }, { slug: "پیش‌نویس-آزمون" }] },
  });
  await prisma.category.deleteMany({
    where: { OR: [{ path: { contains: MARK } }, { slug: { in: ["آزمون-اسلاگ", "آزمون-اسلاگ-2"] } }] },
  });
  await prisma.tag.deleteMany({ where: { OR: [{ slug: { contains: MARK } }, { slug: "آب-رسانی-آزمون" }] } });
}

try {
  await cleanup();

  const postA = await prisma.post.create({
    data: { slug: "تست-تست", title: "آزمون اسلاگ", status: "PUBLISHED" },
    select: { id: true },
  });
  check("12 auto dup post", await resolveUniqueSlug("post", "تست-تست", true, null), "تست-تست-2");
  await prisma.post.create({
    data: { slug: "تست-تست-2", title: "آزمون اسلاگ", status: "PUBLISHED" },
    select: { id: true },
  });
  check("15 chain -3", await resolveUniqueSlug("post", "تست-تست", true, null), "تست-تست-3");
  await prisma.post.create({
    data: { slug: "تست-تست-3", title: "آزمون اسلاگ", status: "PUBLISHED" },
    select: { id: true },
  });
  check("15 chain -4", await resolveUniqueSlug("post", "تست-تست", true, null), "تست-تست-4");

  check("16 manual dup post", await resolveUniqueSlug("post", "تست-تست", false, null), null);
  check("17 edit keep slug", await resolveUniqueSlug("post", "تست-تست", false, postA.id), "تست-تست");
  check("18 edit to taken slug", await resolveUniqueSlug("post", "تست-تست-2", false, postA.id), null);
  check("17 auto exclude self", await resolveUniqueSlug("post", "تست-تست", true, postA.id), "تست-تست");

  const draft = await prisma.post.create({
    data: { slug: "پیش‌نویس-آزمون", title: "پیش‌نویس آزمون", status: "DRAFT" },
    select: { id: true },
  });
  check("19 draft persian slug", (await prisma.post.findUnique({ where: { slug: "پیش‌نویس-آزمون" }, select: { status: true } }))?.status, "DRAFT");
  check("20 publish keeps slug", await resolveUniqueSlug("post", "پیش‌نویس-آزمون", false, draft.id), "پیش‌نویس-آزمون");
  await prisma.post.delete({ where: { id: draft.id } });

  const catA = await prisma.category.create({
    data: { slug: "آزمون-اسلاگ", name: "آزمون اسلاگ", path: "آزمون-اسلاگ" },
    select: { id: true },
  });
  check("13 auto dup category", await resolveUniqueSlug("category", "آزمون-اسلاگ", true, null), "آزمون-اسلاگ-2");
  check("16 manual dup category", await resolveUniqueSlug("category", "آزمون-اسلاگ", false, null), null);
  check("17 category keep", await resolveUniqueSlug("category", "آزمون-اسلاگ", false, catA.id), "آزمون-اسلاگ");
  check("18 category taken", await resolveUniqueSlug("category", "تکنیک‌ها", false, catA.id), null);

  const tagA = await prisma.tag.create({
    data: { slug: "آب-رسانی-آزمون", name: "آب رسانی آزمون" },
    select: { id: true },
  });
  check("14 auto dup tag", await resolveUniqueSlug("tag", "آب-رسانی-آزمون", true, null), "آب-رسانی-آزمون-2");
  check("16 manual dup tag", await resolveUniqueSlug("tag", "آب-رسانی-آزمون", false, null), null);
  check("17 tag keep", await resolveUniqueSlug("tag", "آب-رسانی-آزمون", false, tagA.id), "آب-رسانی-آزمون");

  check("17 legacy zwnj tag untouched", await resolveUniqueSlug("tag", "آب‌رسانی", false, 8), "آب‌رسانی");

  const parent = await prisma.category.create({
    data: { slug: `${MARK}-parent`, name: `${MARK} parent`, path: `${MARK}-parent` },
    select: { id: true },
  });
  const child = await prisma.category.create({
    data: {
      slug: `${MARK}-child`,
      name: `${MARK} child`,
      path: `${MARK}-parent/${MARK}-child`,
      parentId: parent.id,
    },
    select: { id: true },
  });
  const renamed = await resolveUniqueSlug("category", `${MARK}-parent-2`, false, parent.id);
  check("26 parent rename resolves", renamed, `${MARK}-parent-2`);
  await prisma.category.update({ where: { id: parent.id }, data: { slug: renamed!, path: `${MARK}-parent-2` } });
  await prisma.category.update({
    where: { id: child.id },
    data: { path: `${MARK}-parent-2/${MARK}-child` },
  });
  const childAfter = await prisma.category.findUnique({ where: { id: child.id }, select: { path: true } });
  check("26 child path follows", childAfter?.path, `${MARK}-parent-2/${MARK}-child`);
} finally {
  await cleanup();
  await prisma.$disconnect();
}

console.log(failures === 0 ? "\nALL PASS" : `\n${failures} FAILURES`);
process.exit(failures === 0 ? 0 : 1);
