const SLUG_INVISIBLE = /[\u200B\u200D\u200E\u200F\uFEFF]/g;
const SLUG_DISALLOWED = /[^\p{L}\p{N}\u200C-]+/gu;
const SLUG_EDGE = /^[\u200C-]+|[\u200C-]+$/g;

export function normalizeSlug(value: string): string {
  return value
    .normalize("NFC")
    .trim()
    .toLowerCase()
    .replace(SLUG_INVISIBLE, "")
    .replace(/\p{M}/gu, "")
    .replace(SLUG_DISALLOWED, " ")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/\u200C*-\u200C*/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/\u200C{2,}/g, "\u200C")
    .replace(SLUG_EDGE, "");
}

export type SlugResolution =
  | { ok: true; slug: string; autoGenerated: boolean }
  | { ok: false; reason: "empty" | "invalid" };

export function resolveSlug(rawSlug: string, fallbackSource: string): SlugResolution {
  const manual = String(rawSlug ?? "").trim();
  if (manual) {
    const slug = normalizeSlug(manual);
    return slug ? { ok: true, slug, autoGenerated: false } : { ok: false, reason: "invalid" };
  }

  const generated = normalizeSlug(String(fallbackSource ?? ""));
  return generated ? { ok: true, slug: generated, autoGenerated: true } : { ok: false, reason: "empty" };
}

export function uniqueSlugCandidate(base: string, takenSlugs: readonly string[]): string {
  const taken = new Set(takenSlugs);
  if (!taken.has(base)) return base;

  const escaped = base.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const suffixPattern = new RegExp(`^${escaped}-(\\d+)$`, "u");
  let max = 1;
  for (const slug of taken) {
    const match = suffixPattern.exec(slug);
    if (match) max = Math.max(max, Number(match[1]));
  }
  return `${base}-${max + 1}`;
}
