import { uniqueSlugCandidate } from "@/lib/slug";
import { prisma } from "@/lib/prisma";

export type SlugModel = "post" | "category" | "tag";

export async function resolveUniqueSlug(
  model: SlugModel,
  slug: string,
  autoGenerated: boolean,
  excludeId: number | null,
): Promise<string | null> {
  if (model === "post") {
    if (!autoGenerated) {
      const row = await prisma.post.findUnique({ where: { slug }, select: { id: true } });
      return row && row.id !== excludeId ? null : slug;
    }
    const rows = await prisma.post.findMany({
      where: {
        OR: [{ slug }, { slug: { startsWith: `${slug}-` } }],
        ...(excludeId !== null ? { id: { not: excludeId } } : {}),
      },
      select: { slug: true },
    });
    return uniqueSlugCandidate(slug, rows.map((row) => row.slug));
  }

  if (model === "category") {
    if (!autoGenerated) {
      const row = await prisma.category.findUnique({ where: { slug }, select: { id: true } });
      return row && row.id !== excludeId ? null : slug;
    }
    const rows = await prisma.category.findMany({
      where: {
        OR: [{ slug }, { slug: { startsWith: `${slug}-` } }],
        ...(excludeId !== null ? { id: { not: excludeId } } : {}),
      },
      select: { slug: true },
    });
    return uniqueSlugCandidate(slug, rows.map((row) => row.slug));
  }

  if (!autoGenerated) {
    const row = await prisma.tag.findUnique({ where: { slug }, select: { id: true } });
    return row && row.id !== excludeId ? null : slug;
  }
  const rows = await prisma.tag.findMany({
    where: {
      OR: [{ slug }, { slug: { startsWith: `${slug}-` } }],
      ...(excludeId !== null ? { id: { not: excludeId } } : {}),
    },
    select: { slug: true },
  });
  return uniqueSlugCandidate(slug, rows.map((row) => row.slug));
}
