"use server";

import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { PAGES_FORM_LABELS } from "@/data/dashboard/ui";
import type { PageFormState, PageInput } from "@/lib/admin-types";
import { prisma } from "@/lib/prisma";
import { hasSeoData, normalizePageInput, requireSession, revalidatePagePaths } from "./shared";
import type { NormalizedSeo } from "./shared";
import { resolveUniqueSlug } from "@/lib/slug-server";

function isSlugConflict(error: unknown): boolean {
  return error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002";
}

function seoWriteOps(pageId: number, seo: NormalizedSeo) {
  return hasSeoData(seo)
    ? prisma.seoMetadata.upsert({
        where: { pageId },
        create: { pageId, ...seo },
        update: { ...seo },
      })
    : prisma.seoMetadata.deleteMany({ where: { pageId } });
}

export async function createPage(_previousState: PageFormState, input: PageInput): Promise<PageFormState> {
  await requireSession();

  const result = normalizePageInput(input);
  if (!result.ok) return { status: "error", fieldErrors: result.fieldErrors };

  const { data, slugAutoGenerated } = result;
  const slug = await resolveUniqueSlug("page", data.slug, slugAutoGenerated, null);
  if (slug === null) return { status: "error", fieldErrors: { slug: PAGES_FORM_LABELS.slugTaken } };

  const publishedAt = data.status === "PUBLISHED" ? new Date() : null;
  try {
    const { seo, ...pageData } = data;
    const page = await prisma.page.create({
      data: {
        ...pageData,
        slug,
        content: pageData.content ?? Prisma.DbNull,
        publishedAt,
      },
    });
    if (hasSeoData(seo)) {
      await prisma.seoMetadata.create({ data: { pageId: page.id, ...seo } });
    }
  } catch (error) {
    if (isSlugConflict(error)) {
      return { status: "error", fieldErrors: { slug: PAGES_FORM_LABELS.slugTaken } };
    }
    console.error("createPage failed:", error);
    return { status: "error", message: PAGES_FORM_LABELS.error };
  }

  revalidatePagePaths(slug);
  redirect("/dashboard/pages");
}

export async function updatePage(
  _previousState: PageFormState,
  input: PageInput & { currentSlug: string },
): Promise<PageFormState> {
  await requireSession();

  const { currentSlug, ...rawInput } = input;
  const result = normalizePageInput(rawInput);
  if (!result.ok) return { status: "error", fieldErrors: result.fieldErrors };
  const { data, slugAutoGenerated } = result;

  const current = await prisma.page.findUnique({
    where: { slug: currentSlug },
    select: { id: true, status: true, publishedAt: true },
  });
  if (!current) return { status: "error", message: PAGES_FORM_LABELS.error };

  const slug = await resolveUniqueSlug("page", data.slug, slugAutoGenerated, current.id);
  if (slug === null) return { status: "error", fieldErrors: { slug: PAGES_FORM_LABELS.slugTaken } };

  const publishedAt = data.status === "PUBLISHED" ? current.publishedAt ?? new Date() : null;

  try {
    const { seo, ...pageData } = data;
    await prisma.$transaction([
      prisma.page.update({
        where: { id: current.id },
        data: {
          ...pageData,
          slug,
          content: pageData.content === null ? Prisma.DbNull : pageData.content,
          publishedAt,
        },
      }),
      seoWriteOps(current.id, seo),
    ]);
  } catch (error) {
    if (isSlugConflict(error)) {
      return { status: "error", fieldErrors: { slug: PAGES_FORM_LABELS.slugTaken } };
    }
    console.error("updatePage failed:", error);
    return { status: "error", message: PAGES_FORM_LABELS.error };
  }

  revalidatePagePaths(currentSlug);
  if (slug !== currentSlug) revalidatePagePaths(slug);
  redirect("/dashboard/pages");
}

export async function deletePage(slug: string): Promise<{ ok: boolean }> {
  await requireSession();

  try {
    await prisma.page.delete({ where: { slug } });
  } catch {
    return { ok: false };
  }

  revalidatePagePaths(slug);
  revalidatePath("/dashboard");
  return { ok: true };
}
