import { revalidatePath, revalidateTag } from "next/cache";
import { redirect } from "next/navigation";
import { POST_FORM_LABELS, TAXONOMY_LABELS } from "@/data/dashboard/ui";
import { getSession } from "@/lib/auth";
import type {
  PostFieldErrors,
  PostInput,
  PostPublishStatus,
  TaxonomyFieldErrors,
  TaxonomyInput,
} from "@/lib/admin-types";
import { resolveSlug } from "@/lib/slug";
import { sanitizePostHtml } from "@/lib/post-content";

export async function requireSession() {
  const session = await getSession();
  if (!session) redirect("/login");
  return session;
}

export function revalidatePostPaths(slug: string) {
  revalidatePath("/");
  revalidatePath("/blog");
  revalidatePath(`/blog/${slug}`);
  revalidatePath("/dashboard/posts");
  revalidatePath("/dashboard/posts/trash");
  revalidatePath("/dashboard/comments");
  revalidateTag("blog", "max");
  revalidateTag("posts", "max");
  revalidateTag(`post-${slug}`, "max");
}

export function revalidateCommentTargets(slug: string) {
  revalidatePath(`/blog/${slug}`);
  revalidatePath("/dashboard/comments");
  revalidatePath("/dashboard");
  revalidateTag("blog", "max");
  revalidateTag("comments", "max");
}

export function revalidateTaxonomy(kind: "categories" | "tags") {
  revalidatePath("/");
  revalidatePath("/blog");
  revalidatePath(`/dashboard/${kind}`);
  revalidatePath("/dashboard");
  revalidateTag("blog", "max");
  revalidateTag(kind, "max");
}

export function revalidateMedia() {
  revalidatePath("/dashboard/media");
  revalidatePath("/dashboard");
}

export function normalizeOptionalText(value: unknown): string | null {
  const text = String(value ?? "").trim();
  return text.length > 0 ? text : null;
}

export interface NormalizedSeo {
  seoTitle: string | null;
  seoDescription: string | null;
  keywords: string | null;
  canonical: string | null;
}

export function hasSeoData(seo: NormalizedSeo): boolean {
  return seo.seoTitle !== null || seo.seoDescription !== null || seo.keywords !== null || seo.canonical !== null;
}

export function normalizeSeoInput(input: {
  seoTitle?: unknown;
  seoDescription?: unknown;
  keywords?: unknown;
  canonical?: unknown;
}): NormalizedSeo {
  return {
    seoTitle: normalizeOptionalText(input.seoTitle),
    seoDescription: normalizeOptionalText(input.seoDescription),
    keywords: normalizeOptionalText(input.keywords),
    canonical: normalizeOptionalText(input.canonical),
  };
}

export interface NormalizedTaxonomy {
  name: string;
  slug: string;
  parentId: number | null;
  image: string | null;
  imageAlt: string | null;
  description: string | null;
  seo: NormalizedSeo;
}

export type TaxonomyValidationResult =
  | { ok: true; data: NormalizedTaxonomy; slugAutoGenerated: boolean }
  | { ok: false; fieldErrors: TaxonomyFieldErrors; message?: string };

export function normalizeTaxonomyInput(input: TaxonomyInput): TaxonomyValidationResult {
  const fieldErrors: TaxonomyFieldErrors = {};

  const name = String(input.name ?? "").trim();
  if (!name) fieldErrors.name = TAXONOMY_LABELS.nameRequired;

  const slugResolution = resolveSlug(String(input.slug ?? ""), name);
  if (!slugResolution.ok) {
    fieldErrors.slug =
      slugResolution.reason === "empty" ? TAXONOMY_LABELS.slugRequired : TAXONOMY_LABELS.slugInvalid;
  }

  let parentId: number | null = null;
  let parentInvalid = false;
  if (input.parentId !== null && input.parentId !== undefined) {
    const parsed = Number(input.parentId);
    if (!Number.isInteger(parsed) || parsed <= 0) {
      parentInvalid = true;
    } else {
      parentId = parsed;
    }
  }

  if (Object.keys(fieldErrors).length > 0 || parentInvalid) {
    return {
      ok: false,
      fieldErrors,
      ...(parentInvalid ? { message: TAXONOMY_LABELS.parentInvalid } : {}),
    };
  }

  return {
    ok: true,
    slugAutoGenerated: slugResolution.ok && slugResolution.autoGenerated,
    data: {
      name,
      slug: slugResolution.ok ? slugResolution.slug : "",
      parentId,
      image: normalizeOptionalText(input.image),
      imageAlt: normalizeOptionalText(input.imageAlt),
      description: normalizeOptionalText(input.description),
      seo: normalizeSeoInput(input),
    },
  };
}

export interface NormalizedPost {
  title: string;
  slug: string;
  excerpt: string | null;
  categoryIds: number[];
  tagIds: number[];
  readTimeMinutes: number | null;
  content: string | null;
  coverImage: string | null;
  coverImageAlt: string | null;
  seo: NormalizedSeo;
  status: PostPublishStatus;
}

export type PostValidationResult =
  | { ok: true; data: NormalizedPost; slugAutoGenerated: boolean }
  | { ok: false; fieldErrors: PostFieldErrors };

export function normalizePostInput(input: PostInput): PostValidationResult {
  const errors: PostFieldErrors = {};

  const title = String(input.title ?? "").trim();
  if (!title) errors.title = POST_FORM_LABELS.titleRequired;

  const slugResolution = resolveSlug(String(input.slug ?? ""), title);
  if (!slugResolution.ok) {
    errors.slug =
      slugResolution.reason === "empty" ? POST_FORM_LABELS.slugRequired : POST_FORM_LABELS.slugInvalid;
  }

  const categoryIds = Array.isArray(input.categoryIds)
    ? Array.from(
        new Set(
          input.categoryIds
            .map((id) => Number(id))
            .filter((id) => Number.isInteger(id) && id > 0),
        ),
      )
    : [];

  const tagIds = Array.isArray(input.tagIds)
    ? input.tagIds.map((id) => Number(id)).filter((id) => Number.isInteger(id) && id > 0)
    : [];

  const readTimeRaw = String(input.readTimeMinutes ?? "").trim();
  let readTimeMinutes: number | null = null;
  if (readTimeRaw !== "") {
    const parsed = Number(readTimeRaw);
    if (Number.isInteger(parsed) && parsed > 0) {
      readTimeMinutes = parsed;
    } else {
      errors.readTimeMinutes = POST_FORM_LABELS.readTimeInvalid;
    }
  }

  if (Object.keys(errors).length > 0) return { ok: false, fieldErrors: errors };

  const excerpt = String(input.excerpt ?? "").trim();
  const rawContent = String(input.content ?? "").trim();

  return {
    ok: true,
    slugAutoGenerated: slugResolution.ok && slugResolution.autoGenerated,
    data: {
      title,
      slug: slugResolution.ok ? slugResolution.slug : "",
      excerpt: excerpt.length > 0 ? excerpt : null,
      categoryIds,
      tagIds,
      readTimeMinutes,
      content: rawContent.length > 0 ? sanitizePostHtml(rawContent) : null,
      coverImage: normalizeOptionalText(input.coverImage),
      coverImageAlt: normalizeOptionalText(input.coverImageAlt),
      seo: normalizeSeoInput(input),
      status: input.status === "DRAFT" ? "DRAFT" : "PUBLISHED",
    },
  };
}
