"use server";

import { Prisma } from "@prisma/client";
import { redirect } from "next/navigation";
import { TAXONOMY_LABELS } from "@/data/dashboard/ui";
import type { TaxonomyFormState, TaxonomyInput } from "@/lib/admin-types";
import { prisma } from "@/lib/prisma";
import { deleteImage } from "@/lib/r2";
import { resolveUniqueSlug } from "@/lib/slug-server";
import { normalizeTaxonomyInput, requireSession, revalidateTaxonomy } from "./shared";

function toTagData(data: TaxonomyInput) {
  return {
    name: data.name,
    slug: data.slug,
    image: data.image,
    imageAlt: data.imageAlt,
    description: data.description,
    metaTitle: data.metaTitle,
    metaDescription: data.metaDescription,
  };
}

async function saveCategory(id: number | null, data: TaxonomyInput): Promise<string | null> {
  const parentId = data.parentId;
  let parent: { id: number; path: string } | null = null;
  if (parentId !== null) {
    parent = await prisma.category.findUnique({
      where: { id: parentId },
      select: { id: true, path: true },
    });
    if (!parent) return TAXONOMY_LABELS.parentInvalid;
  }

  if (id === null) {
    const path = parent ? `${parent.path}/${data.slug}` : data.slug;
    await prisma.category.create({ data: { ...data, path } });
    return null;
  }

  const existing = await prisma.category.findUnique({ where: { id }, select: { path: true } });
  if (!existing) return TAXONOMY_LABELS.parentInvalid;

  if (parent && (parent.id === id || parent.path.startsWith(`${existing.path}/`))) {
    return TAXONOMY_LABELS.parentCycle;
  }

  const newPath = parent ? `${parent.path}/${data.slug}` : data.slug;

  if (newPath === existing.path) {
    await prisma.category.update({ where: { id }, data });
    return null;
  }

  const descendants = await prisma.category.findMany({
    where: { path: { startsWith: `${existing.path}/` } },
    select: { id: true, path: true },
  });

  await prisma.$transaction([
    prisma.category.update({ where: { id }, data: { ...data, path: newPath } }),
    ...descendants.map((descendant) =>
      prisma.category.update({
        where: { id: descendant.id },
        data: { path: `${newPath}${descendant.path.slice(existing.path.length)}` },
      }),
    ),
  ]);

  return null;
}

export async function saveTaxonomy(
  kind: "category" | "tag",
  id: number | null,
  input: TaxonomyInput,
): Promise<TaxonomyFormState> {
  await requireSession();

  const result = normalizeTaxonomyInput(input);
  if (!result.ok) {
    return { status: "error", fieldErrors: result.fieldErrors, ...(result.message ? { message: result.message } : {}) };
  }
  const { data, slugAutoGenerated } = result;

  const slug = await resolveUniqueSlug(kind, data.slug, slugAutoGenerated, id);
  if (slug === null) return { status: "error", fieldErrors: { slug: TAXONOMY_LABELS.slugTaken } };

  const nameConflict =
    kind === "category"
      ? await prisma.category.findFirst({
          where: { name: data.name, ...(id !== null ? { id: { not: id } } : {}) },
          select: { id: true },
        })
      : await prisma.tag.findFirst({
          where: { name: data.name, ...(id !== null ? { id: { not: id } } : {}) },
          select: { id: true },
        });
  if (nameConflict) return { status: "error", fieldErrors: { name: TAXONOMY_LABELS.nameTaken } };

  const dataWithSlug = { ...data, slug };

  try {
    if (kind === "category") {
      const categoryError = await saveCategory(id, dataWithSlug);
      if (categoryError) return { status: "error", message: categoryError };
    } else if (id === null) {
      await prisma.tag.create({ data: toTagData(dataWithSlug) });
    } else {
      await prisma.tag.update({ where: { id }, data: toTagData(dataWithSlug) });
    }
  } catch (error) {
    if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002") {
      const target = error.meta?.target;
      const fields = Array.isArray(target) ? target.map(String) : [];
      if (fields.includes("name")) {
        return { status: "error", fieldErrors: { name: TAXONOMY_LABELS.nameTaken } };
      }
      return { status: "error", fieldErrors: { slug: TAXONOMY_LABELS.slugTaken } };
    }
    console.error("saveTaxonomy failed:", error);
    return { status: "error", message: TAXONOMY_LABELS.error };
  }

  revalidateTaxonomy(kind === "category" ? "categories" : "tags");
  redirect(`/dashboard/${kind === "category" ? "categories" : "tags"}`);
}

export async function deleteTaxonomy(
  kind: "category" | "tag",
  id: number,
): Promise<{ ok: boolean; reason?: "hasChildren" | "hasPosts" }> {
  await requireSession();

  const existing =
    kind === "category"
      ? await prisma.category.findUnique({ where: { id }, select: { image: true } })
      : await prisma.tag.findUnique({ where: { id }, select: { image: true } });
  if (!existing) return { ok: false };

  try {
    if (kind === "category") {
      const [childCount, postCount] = await Promise.all([
        prisma.category.count({ where: { parentId: id } }),
        prisma.post.count({ where: { categories: { some: { id } } } }),
      ]);
      if (childCount > 0) return { ok: false, reason: "hasChildren" };
      if (postCount > 0) return { ok: false, reason: "hasPosts" };
      await prisma.category.delete({ where: { id } });
    } else {
      await prisma.tag.delete({ where: { id } });
    }
  } catch {
    return { ok: false };
  }

  if (existing.image) {
    await deleteImage(existing.image).catch(() => undefined);
  }

  revalidateTaxonomy(kind === "category" ? "categories" : "tags");
  return { ok: true };
}
